### PR TITLE
Integrate Prettier for Consistent Code Formatting

### PR DESCRIPTION
**Pull request by gokuljs**
Description:

This issue proposes the integration of Prettier into our codebase to achieve consistent code formatting across the entire project. Prettier is a code formatter that automates the process, thus eliminating the need for style-related discussions during code reviews.

Benefits:

Consistent Code Style: Automatically enforces a uniform coding standard.
Efficient Reviews: Reduces time spent on formatting discussions during PR reviews.
Ease of Contribution: Helps new contributors follow our coding standards with less overhead.
Proposed Changes:

Configuration: 

Add a .prettierrc file to the repository with our chosen formatting rules.
Codebase Update: Execute Prettier across the existing codebase to ensure that all files adhere to the new formatting standards.

### CODE REVIEW

**Comment by gokuljs** [comment]
#60

**Comment by HenryHengZJ** [comment]
can we add a script like `format` to kick off the prettier stuff. For example:
```
"format": "prettier --write \"**/*.{js,jsx,ts,tsx,md,mdx}\"",
"format:check": "prettier --check \"**/*.{js,jsx,ts,tsx,md,mdx}\""
```

**Comment by gokuljs** [comment]
Done. I've added the Prettier formatting commands to the package.json:

These commands can now be run manually to forma. Later, I'll set up a separate PR to integrate Husky for pre-commit hooks, which will automate the process of running these commands. This way, we can ensure that all committed code adheres to our formatting standards without requiring manual intervention each time.

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
awesome thanks @gokuljs !

**Pull request merged**
