### PR TITLE
Fixed chatbot icon is not visible bug

### PR DESCRIPTION
**Pull request by amansoni7477030**
There is new issue arrived now chatbot icon is not visible on desktop 
Screenshot from 2024-06-12 19-39-36

This PR will fix that issue

### CODE REVIEW

**Comment by toi500** [comment]
@amansoni7477030 can you confirm that this PR (fix) has disabled the autoFocus by default when you start the embedding chat on mobile?

Previus PR have still this issue https://flowise-test01.surge.sh after the @HenryHengZJ last commit https://github.com/FlowiseAI/FlowiseChatEmbed/pull/183/commits/2f7775e11eeb64c6f291b9b466e0b970494acd76

**Review by HenryHengZJ — APPROVED** [review]
thanks! how did I miss that 😅

**Comment by amansoni7477030** [comment]
> thanks! how did I miss that 😅

No worries, sometimes mistakes happen.

**Comment by amansoni7477030** [comment]
> @amansoni7477030 can you confirm that this PR (fix) has disabled the autoFocus on mobiles by default when you start the embedding chat on mobile?
> 
> Previus PR have still this issue https://flowise-test01.surge.sh after the last @HenryHengZJ commit [2f7775e](https://github.com/FlowiseAI/FlowiseChatEmbed/commit/2f7775e11eeb64c6f291b9b466e0b970494acd76)

@toi500 yes it fixed all the issues

**Comment by toi500** [comment]
Sorry guys for being a pain in the ass about the bloody autofocus haha

**Comment by HenryHengZJ** [comment]
@toi500 it should disabled by default now if on mobile, can you verify again?

**Comment by amansoni7477030** [comment]
> Sorry guys for being a pain in the ass about the bloody autofocus haha

No issue at all, I enjoy the challenges! 😊

**Pull request merged**
